version: "3.3"

services:

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  restapi:
    build: ../restapi
    environment:
      - API_KEY=9IJF3E893E4E2Q2M
      - SECRET_KEY=m(5+#i$uv7y%n9ey!r+mp@jjn(@7*s4*c23er9@&lbiz#55=6a
      - DEBUG=False
      - ALLOWED_HOSTS=*
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: bash -c "python3 manage.py makemigrations backtester
      && python3 manage.py makemigrations strategies
      && python3 manage.py migrate
      && echo yes | python3 manage.py collectstatic
      && gunicorn restapi.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - ../restapi:/home/app/restapi/
    expose:
      - 8000
    depends_on:
      - db

  server:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../restapi/staticfiles/:/home/app/restapi/static/
    depends_on:
      - restapi
    restart: "on-failure"
