version: "3.3"

services:

  db:
    image: postgres
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rest_api:
    build: .
    environment:
      - API_KEY=9IJF3E893E4E2Q2M
    command: bash -c "cron
      && cd AITradingPlatform
      && python3 manage.py makemigrations DataFeeder
      && python3 manage.py makemigrations BackTester
      && python3 manage.py makemigrations PaperTrader
      && python3 manage.py makemigrations Strategies
      && python3 manage.py migrate
      && echo yes | python3 manage.py collectstatic
      && python3 manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/home/app/microservice
    ports:
      - "1300:8000"
    depends_on:
      - db
