from django.db import models

# specify TickData time_period choices
TICK_DATA_TIME_PERIOD_CHOICES = (
    ("1", "daily"),
)

# specify StrategyConfig dimension choices
STRATEGY_CONFIG_DIMENSION_CHOICES = (
    ("1", "close"),
    ("2", "open"),
    ("3", "high"),
    ("4", "low"),
    ("5", "volume"),
    ("6", "N/A"),
)

# specify Signal type choices
SIGNAL_TYPE_CHOICES = (
    ("1", "BUY"),
    ("2", "SELL"),
)


# Example model of no consequence
class ExampleStrategiesModel(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


# Company data - ticker is always Yahoo Finance tickers
class Company(models.Model):
    name = models.CharField(max_length=100)
    ticker = models.CharField(max_length=20)
    description = models.TextField()

    def __str__(self):
        return self.name


# Raw sourced data from Yahoo Finance
class TickerData(models.Model):
    open = models.FloatField()
    high = models.FloatField()
    low = models.FloatField()
    close = models.FloatField()
    volume = models.IntegerField()
    time_stamp = models.DateTimeField()
    company = models.ForeignKey(
        to=Company,
        on_delete=models.CASCADE,
    )
    time_period = models.CharField(
        max_length=20,
        choices=TICK_DATA_TIME_PERIOD_CHOICES,
        default="1",
    )

    def __str__(self):
        return f"{self.time_stamp} {self.company.name} {self.time_period}"


# Indicator Type and description
class IndicatorType(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name


# Strategy type info
class StrategyType(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    stock_selection = models.TextField()
    entry_criteria = models.TextField()
    exit_criteria = models.TextField()
    stop_loss_method = models.TextField()
    take_profit_method = models.TextField()

    def __str__(self):
        return self.name


# Strategy configuration
class StrategyConfig(models.Model):
    strategy_type = models.ForeignKey(to=StrategyType, on_delete=models.CASCADE)
    indicator_time_period = models.IntegerField()
    max_holding_period = models.IntegerField()
    take_profit_factor = models.IntegerField()
    stop_loss_factor = models.IntegerField()
    sigma = models.IntegerField()
    dimension = models.CharField(
        max_length=20,
        choices=STRATEGY_CONFIG_DIMENSION_CHOICES,
        default="1",
    )

    def __str__(self):
        return f"{self.strategy_type.name} {self.dimension} {self.indicator_time_period} {self.sigma}"


# Signal - generated by strategy
class Signal(models.Model):
    type = models.CharField(
        max_length=20,
        choices=SIGNAL_TYPE_CHOICES,
    )
    ticker_data = models.ForeignKey(to=TickerData, on_delete=models.CASCADE)
    strategy_config = models.ForeignKey(to=StrategyConfig, on_delete=models.CASCADE)

    def __str__(self):
        return self.type


# Order - execution of signal
class Order(models.Model):
    signal = models.ForeignKey(to=Signal, on_delete=models.CASCADE)
    ticker_data = models.ForeignKey(to=TickerData, on_delete=models.CASCADE)

    def __str__(self):
        return self.signal


# Trade - Pair of entry and exit orders per signal
class Trade(models.Model):
    entry_order = models.ForeignKey(to=Order, on_delete=models.CASCADE, related_name="entry_order")
    exit_order = models.ForeignKey(to=Order, on_delete=models.CASCADE, related_name="exit_order")
    net_return = models.FloatField()
    return_percent = models.FloatField()

    def __str__(self):
        return f"{self.entry_order} {self.exit_order} {self.return_percent}"


# Visualization Type
class VisualizationType(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name
